version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:14

jobs:
  build-and-test:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install npm
          command: npm install
      - run:
          name: Npm tests
          command: npm test
      - run:
          name: Nyc npm test
          command: nyc npm test
      - store_artifacts:
          path: ./test/results
      - store_artifacts:
          path: ./coverage

workflows:
  version: 2
  build:
    jobs:
      - build-and-test
