version: 2.1
orbs:
  node: circleci/node@4.7.0
workflows:
  build_and_test:
    jobs:
      - node/test:
          version: '16'
          steps:
            - checkout
            - node/install-packages
            - run: npm test
            - run: npm run coverage
            - store_artifacts:
                path: test-results.xml
            - store_artifacts:
                path: coverage/
