version: 2.1
jobs:
  build:
    docker:
      - image: ubuntu:20.04
    steps:
      - checkout
      - run:
          name: Echoing Hello World
          command: echo "Hello, world"
      - run:
          name: List all files in directory
          command: ls -la
      - run:
          name: Adding text to example.txt
          command: echo "Text added to file from command line" > example.txt
      - run:
          name: Cat example.txt
          command: cat example.txt
      - run:
          name: Update and install zip
          command: |
            apt-get update
            apt-get install -y zip unzip
      - run:
          name: Archiving example.txt into artifact.zip
          command: zip artifact.zip example.txt
      - persist_to_workspace:
          root: .
          paths:
            - artifact.zip
      - run:
          name: Extracting artifact.zip
          command: unzip -l artifact.zip
      - run:
          name: Delete example.txt and artifact.zip
          command: |
            rm example.txt
            rm artifact.zip

workflows:
  version: 2
  build:
    jobs:
      - build
